// ===== MOCK DATA =====

const MOCK_LIVE = [
  { id: 1, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Galatasaray", away: "Fenerbahçe", score: "2-1", minute: "67", odds: { h: "1.45", d: "4.20", a: "6.50" }, trend: ["up", "", "down"] },
  { id: 2, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Beşiktaş", away: "Trabzonspor", score: "0-0", minute: "34", odds: { h: "2.10", d: "3.30", a: "3.80" }, trend: ["", "up", ""] },
  { id: 3, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Arsenal", away: "Man City", score: "1-1", minute: "78", odds: { h: "2.75", d: "3.10", a: "2.55" }, trend: ["up", "", "down"] },
  { id: 4, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Liverpool", away: "Chelsea", score: "3-0", minute: "55", odds: { h: "1.25", d: "6.00", a: "10.0" }, trend: ["up", "down", "down"] },
  { id: 5, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Real Madrid", away: "Barcelona", score: "1-2", minute: "82", odds: { h: "2.90", d: "3.40", a: "2.35" }, trend: ["down", "", "up"] },
  { id: 6, league: "Bundesliga", leagueKey: "bl", flag: "🇩🇪", home: "Bayern Münih", away: "Dortmund", score: "2-2", minute: "71", odds: { h: "1.90", d: "3.60", a: "4.10" }, trend: ["", "up", ""] },
  { id: 7, league: "Serie A", leagueKey: "sa", flag: "🇮🇹", home: "Inter Milan", away: "AC Milan", score: "1-0", minute: "45", odds: { h: "2.05", d: "3.30", a: "3.70" }, trend: ["up", "", ""] },
  { id: 8, league: "Ligue 1", leagueKey: "fl", flag: "🇫🇷", home: "PSG", away: "Marseille", score: "4-1", minute: "88", odds: { h: "1.30", d: "5.50", a: "9.00" }, trend: ["up", "down", "down"] },
];

const MOCK_UPCOMING = [
  { id: 101, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Başakşehir", away: "Sivasspor", time: "Bugün 18:30", odds: { h: "1.80", d: "3.60", a: "4.50" }, trend: ["", "", ""] },
  { id: 102, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Kasımpaşa", away: "Ankaragücü", time: "Bugün 20:45", odds: { h: "2.20", d: "3.20", a: "3.50" }, trend: ["", "", ""] },
  { id: 103, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Konyaspor", away: "Alanyaspor", time: "Bugün 19:00", odds: { h: "2.40", d: "3.10", a: "3.00" }, trend: ["", "", ""] },
  { id: 104, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Samsunspor", away: "Rizespor", time: "Bugün 17:00", odds: { h: "2.10", d: "3.30", a: "3.50" }, trend: ["", "", ""] },
  { id: 105, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Adana Demirspor", away: "Gaziantep FK", time: "Yarın 15:00", odds: { h: "2.00", d: "3.40", a: "3.80" }, trend: ["", "", ""] },
  { id: 106, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Hatayspor", away: "Pendikspor", time: "Yarın 17:30", odds: { h: "1.95", d: "3.50", a: "4.00" }, trend: ["", "", ""] },
  { id: 107, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Fatih Karagümrük", away: "İstanbulspor", time: "Yarın 20:00", odds: { h: "1.70", d: "3.70", a: "5.00" }, trend: ["", "", ""] },
  { id: 108, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Fenerbahçe", away: "Kayserispor", time: "2 gün 20:45", odds: { h: "1.35", d: "4.80", a: "8.00" }, trend: ["", "", ""] },
  { id: 201, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Man United", away: "Tottenham", time: "Bugün 21:00", odds: { h: "2.30", d: "3.40", a: "3.00" }, trend: ["", "", ""] },
  { id: 202, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Newcastle", away: "Aston Villa", time: "Yarın 14:00", odds: { h: "2.10", d: "3.50", a: "3.40" }, trend: ["", "", ""] },
  { id: 203, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Brighton", away: "Brentford", time: "Yarın 16:30", odds: { h: "2.20", d: "3.30", a: "3.20" }, trend: ["", "", ""] },
  { id: 204, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "West Ham", away: "Wolves", time: "Yarın 19:00", odds: { h: "2.00", d: "3.40", a: "3.70" }, trend: ["", "", ""] },
  { id: 205, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Everton", away: "Fulham", time: "2 gün 14:00", odds: { h: "2.50", d: "3.20", a: "2.80" }, trend: ["", "", ""] },
  { id: 206, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Crystal Palace", away: "Nottingham", time: "2 gün 16:30", odds: { h: "2.30", d: "3.30", a: "3.10" }, trend: ["", "", ""] },
  { id: 301, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Valencia", away: "Real Betis", time: "Bugün 21:00", odds: { h: "2.50", d: "3.20", a: "2.90" }, trend: ["", "", ""] },
  { id: 302, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Villarreal", away: "Osasuna", time: "Yarın 20:00", odds: { h: "2.00", d: "3.40", a: "3.80" }, trend: ["", "", ""] },
  { id: 303, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Athletic Bilbao", away: "Girona", time: "Yarın 22:00", odds: { h: "2.20", d: "3.30", a: "3.30" }, trend: ["", "", ""] },
  { id: 304, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Real Sociedad", away: "Getafe", time: "2 gün 20:00", odds: { h: "1.75", d: "3.70", a: "4.80" }, trend: ["", "", ""] },
  { id: 305, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Celta Vigo", away: "Rayo Vallecano", time: "2 gün 22:00", odds: { h: "2.30", d: "3.20", a: "3.10" }, trend: ["", "", ""] },
  { id: 401, league: "Bundesliga", leagueKey: "bl", flag: "🇩🇪", home: "Leverkusen", away: "Stuttgart", time: "Bugün 20:30", odds: { h: "1.60", d: "4.10", a: "5.80" }, trend: ["", "", ""] },
  { id: 402, league: "Bundesliga", leagueKey: "bl", flag: "🇩🇪", home: "RB Leipzig", away: "Freiburg", time: "Yarın 15:30", odds: { h: "1.90", d: "3.60", a: "4.20" }, trend: ["", "", ""] },
  { id: 403, league: "Bundesliga", leagueKey: "bl", flag: "🇩🇪", home: "Frankfurt", away: "Wolfsburg", time: "Yarın 18:30", odds: { h: "2.00", d: "3.40", a: "3.80" }, trend: ["", "", ""] },
  { id: 404, league: "Bundesliga", leagueKey: "bl", flag: "🇩🇪", home: "Werder Bremen", away: "Augsburg", time: "2 gün 15:30", odds: { h: "2.20", d: "3.30", a: "3.30" }, trend: ["", "", ""] },
  { id: 405, league: "Bundesliga", leagueKey: "bl", flag: "🇩🇪", home: "Mainz", away: "Hoffenheim", time: "2 gün 18:30", odds: { h: "2.40", d: "3.20", a: "3.00" }, trend: ["", "", ""] },
  { id: 501, league: "Serie A", leagueKey: "sa", flag: "🇮🇹", home: "Juventus", away: "Napoli", time: "Bugün 20:45", odds: { h: "2.30", d: "3.30", a: "3.10" }, trend: ["", "", ""] },
  { id: 502, league: "Serie A", leagueKey: "sa", flag: "🇮🇹", home: "Atalanta", away: "Roma", time: "Yarın 19:00", odds: { h: "2.10", d: "3.40", a: "3.50" }, trend: ["", "", ""] },
  { id: 503, league: "Serie A", leagueKey: "sa", flag: "🇮🇹", home: "Lazio", away: "Torino", time: "Yarın 21:45", odds: { h: "1.80", d: "3.60", a: "4.50" }, trend: ["", "", ""] },
  { id: 504, league: "Serie A", leagueKey: "sa", flag: "🇮🇹", home: "Fiorentina", away: "Sassuolo", time: "2 gün 20:45", odds: { h: "1.75", d: "3.70", a: "4.80" }, trend: ["", "", ""] },
  { id: 505, league: "Serie A", leagueKey: "sa", flag: "🇮🇹", home: "Bologna", away: "Udinese", time: "2 gün 18:30", odds: { h: "2.00", d: "3.40", a: "3.80" }, trend: ["", "", ""] },
  { id: 601, league: "Ligue 1", leagueKey: "fl", flag: "🇫🇷", home: "Monaco", away: "Nice", time: "Bugün 20:00", odds: { h: "2.10", d: "3.30", a: "3.60" }, trend: ["", "", ""] },
  { id: 602, league: "Ligue 1", leagueKey: "fl", flag: "🇫🇷", home: "Lyon", away: "Rennes", time: "Yarın 19:00", odds: { h: "2.30", d: "3.20", a: "3.10" }, trend: ["", "", ""] },
  { id: 603, league: "Ligue 1", leagueKey: "fl", flag: "🇫🇷", home: "Lens", away: "Strasbourg", time: "Yarın 21:00", odds: { h: "1.90", d: "3.50", a: "4.20" }, trend: ["", "", ""] },
  { id: 604, league: "Ligue 1", leagueKey: "fl", flag: "🇫🇷", home: "Nantes", away: "Montpellier", time: "2 gün 19:00", odds: { h: "2.20", d: "3.30", a: "3.30" }, trend: ["", "", ""] },
  { id: 701, league: "Şampiyonlar Ligi", leagueKey: "cl", flag: "🇪🇺", home: "Real Madrid", away: "Man City", time: "Yarın 21:00", odds: { h: "2.30", d: "3.40", a: "2.90" }, trend: ["", "", ""] },
  { id: 702, league: "Şampiyonlar Ligi", leagueKey: "cl", flag: "🇪🇺", home: "Bayern Münih", away: "Arsenal", time: "Yarın 21:00", odds: { h: "2.00", d: "3.50", a: "3.60" }, trend: ["", "", ""] },
  { id: 703, league: "Şampiyonlar Ligi", leagueKey: "cl", flag: "🇪🇺", home: "Barcelona", away: "Inter Milan", time: "2 gün 21:00", odds: { h: "2.10", d: "3.40", a: "3.40" }, trend: ["", "", ""] },
  { id: 704, league: "Şampiyonlar Ligi", leagueKey: "cl", flag: "🇪🇺", home: "PSG", away: "Dortmund", time: "2 gün 21:00", odds: { h: "1.80", d: "3.70", a: "4.50" }, trend: ["", "", ""] },
  { id: 801, league: "Avrupa Ligi", leagueKey: "el", flag: "🇪🇺", home: "Liverpool", away: "Atalanta", time: "Bugün 18:45", odds: { h: "1.70", d: "3.80", a: "5.00" }, trend: ["", "", ""] },
  { id: 802, league: "Avrupa Ligi", leagueKey: "el", flag: "🇪🇺", home: "Roma", away: "Freiburg", time: "Bugün 21:00", odds: { h: "2.10", d: "3.30", a: "3.50" }, trend: ["", "", ""] },
  { id: 803, league: "Avrupa Ligi", leagueKey: "el", flag: "🇪🇺", home: "Sevilla", away: "Juventus", time: "Yarın 21:00", odds: { h: "2.50", d: "3.20", a: "2.80" }, trend: ["", "", ""] },
  { id: 901, league: "Eredivisie", leagueKey: "ned", flag: "🇳🇱", home: "Ajax", away: "PSV", time: "Bugün 18:30", odds: { h: "2.40", d: "3.30", a: "2.95" }, trend: ["", "", ""] },
  { id: 902, league: "Eredivisie", leagueKey: "ned", flag: "🇳🇱", home: "Feyenoord", away: "AZ Alkmaar", time: "Yarın 16:30", odds: { h: "1.85", d: "3.60", a: "4.40" }, trend: ["", "", ""] },
  { id: 1001, league: "Primeira Liga", leagueKey: "por", flag: "🇵🇹", home: "Porto", away: "Benfica", time: "Bugün 22:30", odds: { h: "2.20", d: "3.40", a: "3.20" }, trend: ["", "", ""] },
  { id: 1002, league: "Primeira Liga", leagueKey: "por", flag: "🇵🇹", home: "Sporting CP", away: "Braga", time: "Yarın 22:30", odds: { h: "1.75", d: "3.70", a: "4.80" }, trend: ["", "", ""] },
  { id: 1101, league: "Brezilya Ligi", leagueKey: "bsa", flag: "🇧🇷", home: "Flamengo", away: "Palmeiras", time: "Bugün 00:00", odds: { h: "2.20", d: "3.20", a: "3.30" }, trend: ["", "", ""] },
  { id: 1102, league: "Brezilya Ligi", leagueKey: "bsa", flag: "🇧🇷", home: "Corinthians", away: "Santos", time: "Yarın 00:30", odds: { h: "2.10", d: "3.30", a: "3.50" }, trend: ["", "", ""] },
  { id: 1201, league: "MLS", leagueKey: "mls", flag: "🇺🇸", home: "LA Galaxy", away: "LAFC", time: "Bugün 03:30", odds: { h: "2.30", d: "3.20", a: "3.10" }, trend: ["", "", ""] },
  { id: 1202, league: "MLS", leagueKey: "mls", flag: "🇺🇸", home: "Inter Miami", away: "New York City", time: "Yarın 02:30", odds: { h: "1.90", d: "3.50", a: "4.20" }, trend: ["", "", ""] },
  { id: 1301, league: "Konferans Ligi", leagueKey: "ecl", flag: "🇪🇺", home: "Chelsea", away: "Fiorentina", time: "Bugün 21:00", odds: { h: "2.10", d: "3.30", a: "3.50" }, trend: ["", "", ""] },
  { id: 1302, league: "Konferans Ligi", leagueKey: "ecl", flag: "🇪🇺", home: "Olympiakos", away: "Fenerbahçe", time: "Yarın 21:00", odds: { h: "2.80", d: "3.10", a: "2.50" }, trend: ["", "", ""] },
];

const ODDS_DATA = [
  { league: "Süper Lig", leagueKey: "sl", home: "Galatasaray", away: "Fenerbahçe", o1: "1.45", ox: "4.20", o2: "6.50", alt: "1.85", ust: "1.95", analysis: "Ev sahibi favorisi", badge: "badge-green" },
  { league: "Süper Lig", leagueKey: "sl", home: "Beşiktaş", away: "Trabzonspor", o1: "2.10", ox: "3.30", o2: "3.80", alt: "2.10", ust: "1.72", analysis: "Karşılaşılmış güç", badge: "badge-yellow" },
  { league: "Premier Lig", leagueKey: "pl", home: "Arsenal", away: "Man City", o1: "2.75", ox: "3.10", o2: "2.55", alt: "2.30", ust: "1.60", analysis: "Açık maç", badge: "badge-blue" },
  { league: "Premier Lig", leagueKey: "pl", home: "Liverpool", away: "Chelsea", o1: "1.25", ox: "6.00", o2: "10.0", alt: "2.00", ust: "1.80", analysis: "Kesin ev sahibi", badge: "badge-green" },
  { league: "La Liga", leagueKey: "ll", home: "Real Madrid", away: "Barcelona", o1: "2.90", ox: "3.40", o2: "2.35", alt: "2.20", ust: "1.65", analysis: "Misafir favorisi", badge: "badge-red" },
  { league: "La Liga", leagueKey: "ll", home: "Atletico Madrid", away: "Sevilla", o1: "1.90", ox: "3.50", o2: "4.20", alt: "1.95", ust: "1.85", analysis: "Az gol bekleniyor", badge: "badge-yellow" },
  { league: "Bundesliga", leagueKey: "bl", home: "Bayern Münih", away: "Dortmund", o1: "1.65", ox: "4.00", o2: "5.50", alt: "1.75", ust: "2.05", analysis: "Ev sahibi favorisi", badge: "badge-green" },
  { league: "Süper Lig", leagueKey: "sl", home: "Başakşehir", away: "Sivasspor", o1: "1.80", ox: "3.60", o2: "4.50", alt: "1.85", ust: "1.95", analysis: "Ev sahibi avantajlı", badge: "badge-green" },
];

const AI_PREDICTIONS = [
  {
    id: 1, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷",
    home: "Galatasaray", away: "Fenerbahçe",
    difficulty: "medium", modelScore: 82,
    markets: {
      result: { pick: "1", label: "MS Ev Kazanır", conf: 62, odds: 1.45 },
      ou:     { pick: "Üst", label: "Üst 2.5 Gol", conf: 71, odds: 1.80 },
      btts:   { pick: "Var", label: "KG Var", conf: 68, odds: 1.75 },
      ht:     { pick: "İY 1", label: "İY Ev Önde", conf: 54, odds: 1.90 },
      htft:   { pick: "1/1", label: "İY 1 / MS 1", conf: 49, odds: 2.60 },
    },
    bestPick: "ou",
    reason: "Galatasaray son 5 ev maçında 4 galip, maç başına 2.8 gol ortalaması var."
  },
  {
    id: 2, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    home: "Liverpool", away: "Chelsea",
    difficulty: "easy", modelScore: 91,
    markets: {
      result: { pick: "1", label: "MS Ev Kazanır", conf: 74, odds: 1.25 },
      ou:     { pick: "Üst", label: "Üst 2.5 Gol", conf: 78, odds: 1.68 },
      btts:   { pick: "Var", label: "KG Var", conf: 65, odds: 1.72 },
      ht:     { pick: "İY 1", label: "İY Ev Önde", conf: 69, odds: 1.80 },
      htft:   { pick: "1/1", label: "İY 1 / MS 1", conf: 63, odds: 1.95 },
    },
    bestPick: "ou",
    reason: "Liverpool Anfield'da son 12 maçta 11 galibiyet. Chelsea deplasmanda zayıf."
  },
  {
    id: 3, league: "La Liga", leagueKey: "ll", flag: "🇪🇸",
    home: "Real Madrid", away: "Barcelona",
    difficulty: "hard", modelScore: 44,
    markets: {
      result: { pick: "2", label: "MS Deplasman", conf: 46, odds: 2.35 },
      ou:     { pick: "Üst", label: "Üst 2.5 Gol", conf: 72, odds: 1.70 },
      btts:   { pick: "Var", label: "KG Var", conf: 78, odds: 1.60 },
      ht:     { pick: "İY X", label: "İY Beraberlik", conf: 50, odds: 2.05 },
      htft:   { pick: "X/2", label: "İY X / MS 2", conf: 38, odds: 4.20 },
    },
    bestPick: "btts",
    reason: "El Clasico'da son 6 maçta KG Var 5 kez gerçekleşti."
  },
  {
    id: 4, league: "Bundesliga", leagueKey: "bl", flag: "🇩🇪",
    home: "Bayern Münih", away: "Dortmund",
    difficulty: "easy", modelScore: 88,
    markets: {
      result: { pick: "1", label: "MS Ev Kazanır", conf: 68, odds: 1.65 },
      ou:     { pick: "Üst", label: "Üst 2.5 Gol", conf: 85, odds: 1.55 },
      btts:   { pick: "Var", label: "KG Var", conf: 80, odds: 1.62 },
      ht:     { pick: "İY 1", label: "İY Ev Önde", conf: 64, odds: 1.85 },
      htft:   { pick: "1/1", label: "İY 1 / MS 1", conf: 56, odds: 2.20 },
    },
    bestPick: "ou",
    reason: "Son 8 Der Klassiker'de 7 kez Üst 2.5 gerçekleşti."
  },
  {
    id: 5, league: "Şampiyonlar Ligi", leagueKey: "cl", flag: "🇪🇺",
    home: "Real Madrid", away: "Man City",
    difficulty: "hard", modelScore: 55,
    markets: {
      result: { pick: "1", label: "MS Ev Kazanır", conf: 42, odds: 2.30 },
      ou:     { pick: "Üst", label: "Üst 2.5 Gol", conf: 68, odds: 1.75 },
      btts:   { pick: "Var", label: "KG Var", conf: 72, odds: 1.65 },
      ht:     { pick: "İY X", label: "İY Beraberlik", conf: 48, odds: 2.00 },
      htft:   { pick: "X/1", label: "İY X / MS 1", conf: 35, odds: 3.50 },
    },
    bestPick: "btts",
    reason: "KG Var son 5 Şampiyonlar Ligi karşılaşmasında 4 kez gerçekleşti."
  },
];

const COMPARE_DATA = [
  {
    league: "Süper Lig", leagueKey: "sl", home: "Galatasaray", away: "Fenerbahçe",
    nesine:   { h: "1.45", d: "4.20", a: "6.50" },
    bilyoner: { h: "1.48", d: "4.10", a: "6.30" },
    misli:    { h: "1.50", d: "4.00", a: "6.00" },
    bets10:   { h: "1.43", d: "4.25", a: "6.75" },
  },
  {
    league: "Premier Lig", leagueKey: "pl", home: "Liverpool", away: "Chelsea",
    nesine:   { h: "1.25", d: "6.00", a: "10.00" },
    bilyoner: { h: "1.28", d: "5.80", a: "9.50" },
    misli:    { h: "1.22", d: "6.20", a: "10.50" },
    bets10:   { h: "1.26", d: "5.90", a: "9.80" },
  },
  {
    league: "La Liga", leagueKey: "ll", home: "Real Madrid", away: "Barcelona",
    nesine:   { h: "2.90", d: "3.40", a: "2.35" },
    bilyoner: { h: "2.85", d: "3.45", a: "2.40" },
    misli:    { h: "2.95", d: "3.35", a: "2.30" },
    bets10:   { h: "2.88", d: "3.42", a: "2.38" },
  },
  {
    league: "Bundesliga", leagueKey: "bl", home: "Bayern Münih", away: "Dortmund",
    nesine:   { h: "1.65", d: "4.00", a: "5.50" },
    bilyoner: { h: "1.68", d: "3.90", a: "5.30" },
    misli:    { h: "1.62", d: "4.10", a: "5.70" },
    bets10:   { h: "1.66", d: "3.95", a: "5.40" },
  },
];
