const MOCK_LIVE = [
  { id: 1, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Galatasaray", away: "Fenerbahçe", score: "2-1", minute: "67", odds: { h: "1.45", d: "4.20", a: "6.50" }, trend: ["up", "", "down"] },
  { id: 2, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Beşiktaş", away: "Trabzonspor", score: "0-0", minute: "34", odds: { h: "2.10", d: "3.30", a: "3.80" }, trend: ["", "up", ""] },
  { id: 3, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Arsenal", away: "Man City", score: "1-1", minute: "78", odds: { h: "2.75", d: "3.10", a: "2.55" }, trend: ["up", "", "down"] },
  { id: 4, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Liverpool", away: "Chelsea", score: "3-0", minute: "55", odds: { h: "1.25", d: "6.00", a: "10.0" }, trend: ["up", "down", "down"] },
  { id: 5, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Real Madrid", away: "Barcelona", score: "1-2", minute: "82", odds: { h: "2.90", d: "3.40", a: "2.35" }, trend: ["down", "", "up"] },
  { id: 6, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Atletico Madrid", away: "Sevilla", score: "0-1", minute: "41", odds: { h: "1.90", d: "3.50", a: "4.20" }, trend: ["", "up", ""] },
];

const MOCK_UPCOMING = [
  { id: 101, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Başakşehir", away: "Sivasspor", time: "19:00", odds: { h: "1.80", d: "3.60", a: "4.50" }, trend: ["", "", ""] },
  { id: 102, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Kasımpaşa", away: "Ankaragücü", time: "20:45", odds: { h: "2.20", d: "3.20", a: "3.50" }, trend: ["", "", ""] },
  { id: 103, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Rizespor", away: "Samsunspor", time: "14:00", odds: { h: "2.30", d: "3.20", a: "3.00" }, trend: ["", "", ""] },
  { id: 104, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Hatayspor", away: "Gaziantep", time: "19:00", odds: { h: "2.10", d: "3.10", a: "3.50" }, trend: ["", "", ""] },
  { id: 105, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Kayserispor", away: "Antalyaspor", time: "20:00", odds: { h: "2.50", d: "3.00", a: "2.80" }, trend: ["", "", ""] },
  { id: 106, league: "Süper Lig", leagueKey: "sl", flag: "🇹🇷", home: "Alanyaspor", away: "Konyaspor", time: "16:00", odds: { h: "2.00", d: "3.30", a: "3.80" }, trend: ["", "", ""] },
  { id: 201, league: "TFF 1. Lig", leagueKey: "tff1", flag: "🇹🇷", home: "Eyüpspor", away: "Sakaryaspor", time: "16:30", odds: { h: "1.80", d: "3.40", a: "4.50" }, trend: ["", "", ""] },
  { id: 202, league: "TFF 1. Lig", leagueKey: "tff1", flag: "🇹🇷", home: "Göztepe", away: "Bandırmaspor", time: "19:00", odds: { h: "1.70", d: "3.50", a: "5.00" }, trend: ["", "", ""] },
  { id: 203, league: "TFF 1. Lig", leagueKey: "tff1", flag: "🇹🇷", home: "Manisa FK", away: "Erzurumspor", time: "14:00", odds: { h: "1.90", d: "3.30", a: "4.20" }, trend: ["", "", ""] },
  { id: 204, league: "TFF 1. Lig", leagueKey: "tff1", flag: "🇹🇷", home: "Bodrumspor", away: "Pendikspor", time: "17:00", odds: { h: "2.20", d: "3.10", a: "3.30" }, trend: ["", "", ""] },
  { id: 301, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Manchester City", away: "Liverpool", time: "18:30", odds: { h: "2.10", d: "3.50", a: "3.40" }, trend: ["", "", ""] },
  { id: 302, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Arsenal", away: "Tottenham", time: "16:00", odds: { h: "1.85", d: "3.60", a: "4.50" }, trend: ["", "", ""] },
  { id: 303, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Chelsea", away: "Manchester Utd", time: "20:45", odds: { h: "2.20", d: "3.30", a: "3.30" }, trend: ["", "", ""] },
  { id: 304, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Newcastle", away: "Aston Villa", time: "15:00", odds: { h: "2.00", d: "3.40", a: "3.70" }, trend: ["", "", ""] },
  { id: 305, league: "Premier Lig", leagueKey: "pl", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "West Ham", away: "Brighton", time: "15:00", odds: { h: "2.30", d: "3.20", a: "3.10" }, trend: ["", "", ""] },
  { id: 307, league: "Championship", leagueKey: "ch", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Leeds Utd", away: "Sunderland", time: "16:00", odds: { h: "1.90", d: "3.40", a: "4.20" }, trend: ["", "", ""] },
  { id: 308, league: "Championship", leagueKey: "ch", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", home: "Sheffield Wed", away: "Middlesbrough", time: "16:00", odds: { h: "2.30", d: "3.10", a: "3.10" }, trend: ["", "", ""] },
  { id: 401, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Real Madrid", away: "Barcelona", time: "21:00", odds: { h: "2.30", d: "3.40", a: "3.10" }, trend: ["", "", ""] },
  { id: 402, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Atletico Madrid", away: "Sevilla", time: "19:00", odds: { h: "1.80", d: "3.50", a: "4.60" }, trend: ["", "", ""] },
  { id: 403, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Valencia", away: "Villarreal", time: "17:30", odds: { h: "2.40", d: "3.20", a: "2.90" }, trend: ["", "", ""] },
  { id: 404, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Real Sociedad", away: "Athletic Bilbao", time: "21:00", odds: { h: "2.20", d: "3.30", a: "3.30" }, trend: ["", "", ""] },
  { id: 405, league: "La Liga", leagueKey: "ll", flag: "🇪🇸", home: "Betis", away: "Celta Vigo", time: "18:30", odds: { h: "1.95", d: "3.40", a: "4.00" }, trend: ["", "", ""] },
  { id: 501, league: "Bundesliga", leagueKey: "bl", flag: "🇩🇪", home: "Bayern Münih", away: "Borussia Dortmund", time: "18:30", odds: { h: "1.70", d: "3.80", a: "5.00" }, trend: ["", "", ""] },
  { id: 502, league: "Bundesliga", leagueKey: "bl", flag: "🇩🇪", home: "Bayer Leverkusen", away: "RB Leipzig", time: "15:30", odds: { h: "2.00", d: "3.40", a: "3.70" }, trend: ["", "", ""] },
  { id: 503, league: "Bundesliga", leagueKey: "bl", flag: "🇩🇪", home: "Stuttgart", away: "Hoffenheim", time: "15:30", odds: { h: "1.95", d: "3.30", a: "4.00" }, trend: ["", "", ""] },
  { id: 601, league: "Serie A", leagueKey: "sa", flag: "🇮🇹", home: "Inter Milan", away: "Juventus", time: "20:45", odds: { h: "2.00", d: "3.40", a: "3.80" }, trend: ["", "", ""] },
  { id: 602, league: "Serie A", leagueKey: "sa", flag: "🇮🇹", home: "AC Milan", away: "Napoli", time: "18:00", odds: { h: "2.20", d: "3.30", a: "3.30" }, trend: ["", "", ""] },
  { id: 603, league: "Serie A", leagueKey: "sa", flag: "🇮🇹", home: "Roma", away: "Lazio", time: "20:45", odds: { h: "2.30", d: "3.20", a: "3.10" }, trend: ["", "", ""] },
  { id: 604, league: "Serie A", leagueKey: "sa", flag: "🇮🇹", home: "Atalanta", away: "Fiorentina", time: "15:00", odds: { h: "1.90", d: "3.40", a: "4.20" }, trend: ["", "", ""] },
  { id: 701, league: "Ligue 1", leagueKey: "fl", flag: "🇫🇷", home: "PSG", away: "Marseille", time: "21:00", odds: { h: "1.55", d: "3.90", a: "6.00" }, trend: ["", "", ""] },
  { id: 702, league: "Ligue 1", leagueKey: "fl", flag: "🇫🇷", home: "Lyon", away: "Monaco", time: "19:00", odds: { h: "2.20", d: "3.30", a: "3.30" }, trend: ["", "", ""] },
  { id: 703, league: "Ligue 1", leagueKey: "fl", flag: "🇫🇷", home: "Lille", away: "Nice", time: "17:00", odds: { h: "2.00", d: "3.40", a: "3.70" }, trend: ["", "", ""] },
  { id: 801, league: "Şampiyonlar Ligi", leagueKey: "cl", flag: "🇪🇺", home: "Real Madrid", away: "Man City", time: "21:00", odds: { h: "2.40", d: "3.40", a: "2.90" }, trend: ["", "", ""] },
  { id: 802, league: "Şampiyonlar Ligi", leagueKey: "cl", flag: "🇪🇺", home: "Bayern Münih", away: "Arsenal", time: "21:00", odds: { h: "1.90", d: "3.50", a: "4.10" }, trend: ["", "", ""] },
  { id: 803, league: "Şampiyonlar Ligi", leagueKey: "cl", flag: "🇪🇺", home: "Inter Milan", away: "Atletico", time: "21:00", odds: { h: "2.10", d: "3.30", a: "3.50" }, trend: ["", "", ""] },
  { id: 804, league: "Şampiyonlar Ligi", leagueKey: "cl", flag: "🇪🇺", home: "PSG", away: "Barcelona", time: "21:00", odds: { h: "2.20", d: "3.40", a: "3.20" }, trend: ["", "", ""] },
  { id: 901, league: "Eredivisie", leagueKey: "ned", flag: "🇳🇱", home: "Ajax", away: "PSV", time: "18:45", odds: { h: "2.10", d: "3.40", a: "3.40" }, trend: ["", "", ""] },
  { id: 902, league: "Eredivisie", leagueKey: "ned", flag: "🇳🇱", home: "Feyenoord", away: "AZ Alkmaar", time: "16:30", odds: { h: "1.85", d: "3.50", a: "4.50" }, trend: ["", "", ""] },
  { id: 1001, league: "Primeira Liga", leagueKey: "por", flag: "🇵🇹", home: "Benfica", away: "Porto", time: "21:30", odds: { h: "2.20", d: "3.30", a: "3.30" }, trend: ["", "", ""] },
  { id: 1002, league: "Primeira Liga", leagueKey: "por", flag: "🇵🇹", home: "Sporting CP", away: "Braga", time: "19:00", odds: { h: "1.80", d: "3.50", a: "4.60" }, trend: ["", "", ""] },
  { id: 1101, league: "Belçika Pro League", leagueKey: "bel", flag: "🇧🇪", home: "Club Brugge", away: "Anderlecht", time: "18:30", odds: { h: "2.00", d: "3.40", a: "3.70" }, trend: ["", "", ""] },
  { id: 1201, league: "İskoçya Premiership", leagueKey: "sco", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", home: "Celtic", away: "Rangers", time: "13:30", odds: { h: "1.75", d: "3.60", a: "4.80" }, trend: ["", "", ""] },
];

const ODDS_DATA = [
  { league: "Süper Lig", leagueKey: "sl", home: "Galatasaray", away: "Fenerbahçe", o1: "1.45", ox: "4.20", o2: "6.50", alt: "1.85", ust: "1.95", analysis: "Ev sahibi favorisi", badge: "badge-green" },
  { league: "Süper Lig", leagueKey: "sl", home: "Beşiktaş", away: "Trabzonspor", o1: "2.10", ox: "3.30", o2: "3.80", alt: "2.10", ust: "1.72", analysis: "Karşılaşılmış güç", badge: "badge-yellow" },
  { league: "Premier Lig", leagueKey: "pl", home: "Arsenal", away: "Man City", o1: "2.75", ox: "3.10", o2: "2.55", alt: "2.30", ust: "1.60", analysis: "Açık maç", badge: "badge-blue" },
  { league: "Premier Lig", leagueKey: "pl", home: "Liverpool", away: "Chelsea", o1: "1.25", ox: "6.00", o2: "10.0", alt: "2.00", ust: "1.80", analysis: "Kesin ev sahibi", badge: "badge-green" },
  { league: "La Liga", leagueKey: "ll", home: "Real Madrid", away: "Barcelona", o1: "2.90", ox: "3.40", o2: "2.35", alt: "2.20", ust: "1.65", analysis: "Misafir favorisi", badge: "badge-red" },
  { league: "La Liga", leagueKey: "ll", home: "Atletico Madrid", away: "Sevilla", o1: "1.90", ox: "3.50", o2: "4.20", alt: "1.95", ust: "1.85", analysis: "Az gol bekleniyor", badge: "badge-yellow" },
  { league: "Bundesliga", leagueKey: "bl", home: "Bayern Münih", away: "Dortmund", o1: "1.65", ox: "4.00", o2: "5.50", alt: "1.75", ust: "2.05", analysis: "Ev sahibi favorisi", badge: "badge-green" },
  { league: "Süper Lig", leagueKey: "sl", home: "Başakşehir", away: "Sivasspor", o1: "1.80", ox: "3.60", o2: "4.50", alt: "1.85", ust: "1.95", analysis: "Ev sahibi avantajlı", badge: "badge-green" },
];

const COMPARE_DATA = [
  { league: "Süper Lig", leagueKey: "sl", home: "Galatasaray", away: "Fenerbahçe", nesine: { h: "1.45", d: "4.20", a: "6.50" }, bilyoner: { h: "1.48", d: "4.10", a: "6.30" }, misli: { h: "1.50", d: "4.00", a: "6.00" }, bets10: { h: "1.43", d: "4.25", a: "6.75" } },
  { league: "Süper Lig", leagueKey: "sl", home: "Beşiktaş", away: "Trabzonspor", nesine: { h: "2.10", d: "3.30", a: "3.80" }, bilyoner: { h: "2.15", d: "3.25", a: "3.70" }, misli: { h: "2.08", d: "3.35", a: "3.85" }, bets10: { h: "2.12", d: "3.28", a: "3.75" } },
  { league: "Premier Lig", leagueKey: "pl", home: "Arsenal", away: "Man City", nesine: { h: "2.75", d: "3.10", a: "2.55" }, bilyoner: { h: "2.80", d: "3.05", a: "2.50" }, misli: { h: "2.70", d: "3.15", a: "2.60" }, bets10: { h: "2.85", d: "3.00", a: "2.48" } },
  { league: "La Liga", leagueKey: "ll", home: "Real Madrid", away: "Barcelona", nesine: { h: "2.90", d: "3.40", a: "2.35" }, bilyoner: { h: "2.85", d: "3.45", a: "2.40" }, misli: { h: "2.95", d: "3.35", a: "2.30" }, bets10: { h: "2.88", d: "3.42", a: "2.38" } },
  { league: "Bundesliga", leagueKey: "bl", home: "Bayern Münih", away: "Dortmund", nesine: { h: "1.65", d: "4.00", a: "5.50" }, bilyoner: { h: "1.68", d: "3.90", a: "5.30" }, misli: { h: "1.62", d: "4.10", a: "5.70" }, bets10: { h: "1.66", d: "3.95", a: "5.40" } },
];
